version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

  app:
    build: .
    container_name: betweenle-hebrew
    ports:
      - '3030:3030'
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
