services:
  - type: redis
    name: redis-server
    plan: free # or select the appropriate plan for your needs
    ipAllowList: []

  - type: web
    name: betweenle-hebrew
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t betweenle-hebrew .
    startCommand: node ./dist/index.js
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-server
          property: connectionString
    ports:
      - port: 3030
        protocol: tcp
